---
title: "Inference from the deepaas API interface"
format:
    html:
       toc: true
       toc-location: right
       fontsize: 0.8em
---

## Classifier

Browse to the API exposed by the deepaas service <https://inference-walton.cloud.imagine-ai.eu/system/services/zooprocess-multiple-classifier/exposed/main/api>

All endpoints (i.e. functions) are described and you can try them, directly in the browser. For example, to get information about what the service does, you can get the metadata from the [`GET /v2/models/zooprocess_multiple_classifier/`](https://inference-walton.cloud.imagine-ai.eu/system/services/zooprocess-multiple-classifier/exposed/main/api#/models/get_system_services_zooprocess_multiple_classifier_exposed_main_v2_models_) endpoint. Click "Try it out" and then "Execute".

The `/train` endpoint does not work currently. Only the `/predict` one does. This means that you can test our model with your data but you cannot (yet) re-train a custom model for your particular data. Our model has been trained on a variety of samples and should be satisfactory in many cases.

To try it out, go to the [`POST /v2/models/zooprocess_multiple_classifier/predict/`](https://inference-walton.cloud.imagine-ai.eu/system/services/zooprocess-multiple-classifier/exposed/main/api#/models/post_system_services_zooprocess_multiple_classifier_exposed_main_v2_models_zooprocess_multiple_classifier_predict_) endpoint.

1.  Click "Try it out" as before.
2.  Choose a file among the test images (those starting with "s" are images of single objects, those starting with "m" contain multiple objects).
3.  You can change the amount of pixels to crop at the bottom; 31 is the default to remove the scale bar added by ZooProcess but if you have raw ROIs from the scan, you probably want to set that to 0.
4.  Click "Execute"

The result is a JSON message containing the name of the uploaded file and the probability of it being a multiple. Try it with `s_` or `m_` files to check how relevant the probability is.

Redo the same steps but upload a zip file containing the images instead of just one image. The result now becomes a vector of names and of probabilities. You can now check the relevance of the probability on all images at once.

## Separator

The general process is exactly the same. The endpoint is now [`POST /v2/models/zooprocess_multiple_separator/predict/`](https://inference-walton.cloud.imagine-ai.eu/system/services/zooprocess-multiple-separator/exposed/main/api#/models/post_system_services_zooprocess_multiple_separator_exposed_main_v2_models_zooprocess_multiple_separator_predict_). Try it with an `m_` file.

The output is now more complicated. It contains a `status` field and a `predictions` field, which is a list of predictions; the relevant results are there.

Each `prediction`, contains:

-   `name`: the name of the input image
-   `separation_coordinates`: a list of vectors, the combination of which defines the pixel coordinates (on 0-based indexes) where separation lines should be drawn, in the original input image.
-   `image_shape`: the number of rows and columns of the original image
-   `score`: the average detection score of all objects considered; this is a (poor but not useless) of the confidence in the separation.
